/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.projects;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.types.ProjectInfoResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncProjectsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawProjectsClient rawClient;

    public AsyncProjectsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawProjectsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawProjectsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<ProjectInfoResponse> retrieveInfo() {
        return this.rawClient.retrieveInfo().thenApply(response -> response.body());
    }

    public CompletableFuture<ProjectInfoResponse> retrieveInfo(RequestOptions requestOptions) {
        return this.rawClient.retrieveInfo(requestOptions).thenApply(response -> response.body());
    }
}
