/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum AppAuthType {
    KEYS("keys"),

    OAUTH("oauth"),

    NONE("none");

    private final String value;

    AppAuthType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
