/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BackendClientOpts.Builder.class)
public final class BackendClientOpts {
    private final Optional<String> clientId;

    private final Optional<String> clientSecret;

    private final Optional<String> apiUrl;

    private final Map<String, Object> additionalProperties;

    private BackendClientOpts(
            Optional<String> clientId,
            Optional<String> clientSecret,
            Optional<String> apiUrl,
            Map<String, Object> additionalProperties) {
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.apiUrl = apiUrl;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The client ID for authentication
     */
    @JsonProperty("client_id")
    public Optional<String> getClientId() {
        return clientId;
    }

    /**
     * @return The client secret for authentication
     */
    @JsonProperty("client_secret")
    public Optional<String> getClientSecret() {
        return clientSecret;
    }

    /**
     * @return The API URL to use
     */
    @JsonProperty("api_url")
    public Optional<String> getApiUrl() {
        return apiUrl;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BackendClientOpts && equalTo((BackendClientOpts) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BackendClientOpts other) {
        return clientId.equals(other.clientId)
                && clientSecret.equals(other.clientSecret)
                && apiUrl.equals(other.apiUrl);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.clientId, this.clientSecret, this.apiUrl);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> clientId = Optional.empty();

        private Optional<String> clientSecret = Optional.empty();

        private Optional<String> apiUrl = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BackendClientOpts other) {
            clientId(other.getClientId());
            clientSecret(other.getClientSecret());
            apiUrl(other.getApiUrl());
            return this;
        }

        /**
         * <p>The client ID for authentication</p>
         */
        @JsonSetter(value = "client_id", nulls = Nulls.SKIP)
        public Builder clientId(Optional<String> clientId) {
            this.clientId = clientId;
            return this;
        }

        public Builder clientId(String clientId) {
            this.clientId = Optional.ofNullable(clientId);
            return this;
        }

        /**
         * <p>The client secret for authentication</p>
         */
        @JsonSetter(value = "client_secret", nulls = Nulls.SKIP)
        public Builder clientSecret(Optional<String> clientSecret) {
            this.clientSecret = clientSecret;
            return this;
        }

        public Builder clientSecret(String clientSecret) {
            this.clientSecret = Optional.ofNullable(clientSecret);
            return this;
        }

        /**
         * <p>The API URL to use</p>
         */
        @JsonSetter(value = "api_url", nulls = Nulls.SKIP)
        public Builder apiUrl(Optional<String> apiUrl) {
            this.apiUrl = apiUrl;
            return this;
        }

        public Builder apiUrl(String apiUrl) {
            this.apiUrl = Optional.ofNullable(apiUrl);
            return this;
        }

        public BackendClientOpts build() {
            return new BackendClientOpts(clientId, clientSecret, apiUrl, additionalProperties);
        }
    }
}
