/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ConfigurablePropAlertAlertType {
    INFO("info"),

    NEUTRAL("neutral"),

    WARNING("warning"),

    ERROR("error");

    private final String value;

    ConfigurablePropAlertAlertType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
