/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetTriggerWorkflowsResponse.Builder.class)
public final class GetTriggerWorkflowsResponse {
    private final List<String> workflowIds;

    private final Map<String, Object> additionalProperties;

    private GetTriggerWorkflowsResponse(List<String> workflowIds, Map<String, Object> additionalProperties) {
        this.workflowIds = workflowIds;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("workflow_ids")
    public List<String> getWorkflowIds() {
        return workflowIds;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetTriggerWorkflowsResponse && equalTo((GetTriggerWorkflowsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetTriggerWorkflowsResponse other) {
        return workflowIds.equals(other.workflowIds);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.workflowIds);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<String> workflowIds = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetTriggerWorkflowsResponse other) {
            workflowIds(other.getWorkflowIds());
            return this;
        }

        @JsonSetter(value = "workflow_ids", nulls = Nulls.SKIP)
        public Builder workflowIds(List<String> workflowIds) {
            this.workflowIds.clear();
            this.workflowIds.addAll(workflowIds);
            return this;
        }

        public Builder addWorkflowIds(String workflowIds) {
            this.workflowIds.add(workflowIds);
            return this;
        }

        public Builder addAllWorkflowIds(List<String> workflowIds) {
            this.workflowIds.addAll(workflowIds);
            return this;
        }

        public GetTriggerWorkflowsResponse build() {
            return new GetTriggerWorkflowsResponse(workflowIds, additionalProperties);
        }
    }
}
