/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = StartConnectOpts.Builder.class)
public final class StartConnectOpts {
    private final Optional<String> iframe;

    private final Map<String, Object> additionalProperties;

    private StartConnectOpts(Optional<String> iframe, Map<String, Object> additionalProperties) {
        this.iframe = iframe;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ID of the iframe element to use
     */
    @JsonProperty("iframe")
    public Optional<String> getIframe() {
        return iframe;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof StartConnectOpts && equalTo((StartConnectOpts) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(StartConnectOpts other) {
        return iframe.equals(other.iframe);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.iframe);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> iframe = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(StartConnectOpts other) {
            iframe(other.getIframe());
            return this;
        }

        /**
         * <p>ID of the iframe element to use</p>
         */
        @JsonSetter(value = "iframe", nulls = Nulls.SKIP)
        public Builder iframe(Optional<String> iframe) {
            this.iframe = iframe;
            return this;
        }

        public Builder iframe(String iframe) {
            this.iframe = Optional.ofNullable(iframe);
            return this;
        }

        public StartConnectOpts build() {
            return new StartConnectOpts(iframe, additionalProperties);
        }
    }
}
