/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.components;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.resources.components.requests.ComponentsConfigurePropRequest;
import com.pipedream.api.resources.components.requests.ComponentsListRequest;
import com.pipedream.api.resources.components.requests.ComponentsReloadPropsRequest;
import com.pipedream.api.types.Component;
import com.pipedream.api.types.ConfigurePropResponse;
import com.pipedream.api.types.ReloadPropsResponse;

public class ComponentsClient {
    protected final ClientOptions clientOptions;

    private final RawComponentsClient rawClient;

    public ComponentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawComponentsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawComponentsClient withRawResponse() {
        return this.rawClient;
    }

    public SyncPagingIterable<Component> list() {
        return this.rawClient.list().body();
    }

    public SyncPagingIterable<Component> list(ComponentsListRequest request) {
        return this.rawClient.list(request).body();
    }

    public SyncPagingIterable<Component> list(ComponentsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    public Component retrieve(String componentId) {
        return this.rawClient.retrieve(componentId).body();
    }

    public Component retrieve(String componentId, RequestOptions requestOptions) {
        return this.rawClient.retrieve(componentId, requestOptions).body();
    }

    public ConfigurePropResponse configureProp(ComponentsConfigurePropRequest request) {
        return this.rawClient.configureProp(request).body();
    }

    public ConfigurePropResponse configureProp(ComponentsConfigurePropRequest request, RequestOptions requestOptions) {
        return this.rawClient.configureProp(request, requestOptions).body();
    }

    public ReloadPropsResponse reloadProps(ComponentsReloadPropsRequest request) {
        return this.rawClient.reloadProps(request).body();
    }

    public ReloadPropsResponse reloadProps(ComponentsReloadPropsRequest request, RequestOptions requestOptions) {
        return this.rawClient.reloadProps(request, requestOptions).body();
    }
}
