/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.Environment;
import com.pipedream.api.core.OAuthTokenSupplier;
import com.pipedream.api.resources.oauthtokens.OauthTokensClient;
import java.util.Optional;
import okhttp3.OkHttpClient;

public class AsyncBaseClientBuilder<T extends AsyncBaseClientBuilder<T>> {
    private Optional<Integer> timeout = Optional.empty();

    private Optional<Integer> maxRetries = Optional.empty();

    private String clientId = System.getenv("PIPEDREAM_CLIENT_ID");

    private String clientSecret = System.getenv("PIPEDREAM_CLIENT_SECRET");

    private String projectEnvironment = null;

    private Environment environment = Environment.PROD;

    private OkHttpClient httpClient;

    /**
     * Sets clientId.
     * Defaults to the PIPEDREAM_CLIENT_ID environment variable.
     */
    @SuppressWarnings("unchecked")
    public T clientId(String clientId) {
        this.clientId = clientId;
        return (T) this;
    }

    /**
     * Sets clientSecret.
     * Defaults to the PIPEDREAM_CLIENT_SECRET environment variable.
     */
    @SuppressWarnings("unchecked")
    public T clientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
        return (T) this;
    }

    /**
     * Sets projectEnvironment
     */
    @SuppressWarnings("unchecked")
    public T projectEnvironment(String projectEnvironment) {
        this.projectEnvironment = projectEnvironment;
        return (T) this;
    }

    @SuppressWarnings("unchecked")
    public T environment(Environment environment) {
        this.environment = environment;
        return (T) this;
    }

    @SuppressWarnings("unchecked")
    public T url(String url) {
        this.environment = Environment.custom(url);
        return (T) this;
    }

    /**
     * Sets the timeout (in seconds) for the client. Defaults to 60 seconds.
     */
    @SuppressWarnings("unchecked")
    public T timeout(int timeout) {
        this.timeout = Optional.of(timeout);
        return (T) this;
    }

    /**
     * Sets the maximum number of retries for the client. Defaults to 2 retries.
     */
    @SuppressWarnings("unchecked")
    public T maxRetries(int maxRetries) {
        this.maxRetries = Optional.of(maxRetries);
        return (T) this;
    }

    /**
     * Sets the underlying OkHttp client
     */
    @SuppressWarnings("unchecked")
    public T httpClient(OkHttpClient httpClient) {
        this.httpClient = httpClient;
        return (T) this;
    }

    protected ClientOptions buildClientOptions() {
        ClientOptions.Builder builder = ClientOptions.builder();
        setEnvironment(builder);
        setAuthentication(builder);
        setCustomHeaders(builder);
        setVariables(builder);
        setHttpClient(builder);
        setTimeouts(builder);
        setRetries(builder);
        setAdditional(builder);
        return builder.build();
    }

    /**
     * Sets the environment configuration for the client.
     * Override this method to modify URLs or add environment-specific logic.
     *
     * @param builder The ClientOptions.Builder to configure
     */
    protected void setEnvironment(ClientOptions.Builder builder) {
        builder.environment(this.environment);
    }

    /**
     * Override this method to customize authentication.
     * This method is called during client options construction to set up authentication headers.
     *
     * @param builder The ClientOptions.Builder to configure
     *
     * Example:
     * <pre>{@code
     * @Override
     * protected void setAuthentication(ClientOptions.Builder builder) {
     *     super.setAuthentication(builder); // Keep existing auth
     *     builder.addHeader("X-API-Key", this.apiKey);
     * }
     * }</pre>
     */
    protected void setAuthentication(ClientOptions.Builder builder) {
        if (this.clientId != null && this.clientSecret != null) {
            OauthTokensClient authClient = new OauthTokensClient(
                    ClientOptions.builder().environment(this.environment).build());
            OAuthTokenSupplier oAuthTokenSupplier =
                    new OAuthTokenSupplier(this.clientId, this.clientSecret, authClient);
            builder.addHeader("Authorization", oAuthTokenSupplier);
        }
    }

    /**
     * Override this method to add or modify custom headers.
     * This method is called during client options construction to set up custom headers defined in the API.
     *
     * @param builder The ClientOptions.Builder to configure
     *
     * Example:
     * <pre>{@code
     * @Override
     * protected void setCustomHeaders(ClientOptions.Builder builder) {
     *     super.setCustomHeaders(builder); // Keep existing headers
     *     builder.addHeader("X-Trace-ID", generateTraceId());
     * }
     * }</pre>
     */
    protected void setCustomHeaders(ClientOptions.Builder builder) {
        if (this.projectEnvironment != null) {
            builder.addHeader("x-pd-environment", this.projectEnvironment);
        }
    }

    /**
     * Override this method to configure API variables defined in the specification.
     * Available variables: projectId
     *
     * @param builder The ClientOptions.Builder to configure
     */
    protected void setVariables(ClientOptions.Builder builder) {}

    /**
     * Sets the request timeout configuration.
     * Override this method to customize timeout behavior.
     *
     * @param builder The ClientOptions.Builder to configure
     */
    protected void setTimeouts(ClientOptions.Builder builder) {
        if (this.timeout.isPresent()) {
            builder.timeout(this.timeout.get());
        }
    }

    /**
     * Sets the retry configuration for failed requests.
     * Override this method to implement custom retry strategies.
     *
     * @param builder The ClientOptions.Builder to configure
     */
    protected void setRetries(ClientOptions.Builder builder) {
        if (this.maxRetries.isPresent()) {
            builder.maxRetries(this.maxRetries.get());
        }
    }

    /**
     * Sets the OkHttp client configuration.
     * Override this method to customize HTTP client behavior (interceptors, connection pools, etc).
     *
     * @param builder The ClientOptions.Builder to configure
     */
    protected void setHttpClient(ClientOptions.Builder builder) {
        if (this.httpClient != null) {
            builder.httpClient(this.httpClient);
        }
    }

    /**
     * Override this method to add any additional configuration to the client.
     * This method is called at the end of the configuration chain, allowing you to add
     * custom headers, modify settings, or perform any other client customization.
     *
     * @param builder The ClientOptions.Builder to configure
     *
     * Example:
     * <pre>{@code
     * @Override
     * protected void setAdditional(ClientOptions.Builder builder) {
     *     builder.addHeader("X-Request-ID", () -> UUID.randomUUID().toString());
     *     builder.addHeader("X-Client-Version", "1.0.0");
     * }
     * }</pre>
     */
    protected void setAdditional(ClientOptions.Builder builder) {}

    /**
     * Override this method to add custom validation logic before the client is built.
     * This method is called at the beginning of the build() method to ensure the configuration is valid.
     * Throw an exception to prevent client creation if validation fails.
     *
     * Example:
     * <pre>{@code
     * @Override
     * protected void validateConfiguration() {
     *     super.validateConfiguration(); // Run parent validations
     *     if (tenantId == null || tenantId.isEmpty()) {
     *         throw new IllegalStateException("tenantId is required");
     *     }
     * }
     * }</pre>
     */
    protected void validateConfiguration() {}

    public AsyncBaseClient build() {
        validateConfiguration();
        return new AsyncBaseClient(buildClientOptions());
    }
}
