/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.tokens.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import com.pipedream.api.types.ValidateTokenParams;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TokensValidateRequest.Builder.class)
public final class TokensValidateRequest {
    private final Optional<ValidateTokenParams> params;

    private final Map<String, Object> additionalProperties;

    private TokensValidateRequest(Optional<ValidateTokenParams> params, Map<String, Object> additionalProperties) {
        this.params = params;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("params")
    public Optional<ValidateTokenParams> getParams() {
        return params;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TokensValidateRequest && equalTo((TokensValidateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TokensValidateRequest other) {
        return params.equals(other.params);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.params);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ValidateTokenParams> params = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TokensValidateRequest other) {
            params(other.getParams());
            return this;
        }

        @JsonSetter(value = "params", nulls = Nulls.SKIP)
        public Builder params(Optional<ValidateTokenParams> params) {
            this.params = params;
            return this;
        }

        public Builder params(ValidateTokenParams params) {
            this.params = Optional.ofNullable(params);
            return this;
        }

        public TokensValidateRequest build() {
            return new TokensValidateRequest(params, additionalProperties);
        }
    }
}
