/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.triggers;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.resources.triggers.requests.DeployTriggerOpts;
import com.pipedream.api.resources.triggers.requests.TriggersConfigurePropRequest;
import com.pipedream.api.resources.triggers.requests.TriggersListRequest;
import com.pipedream.api.resources.triggers.requests.TriggersReloadPropsRequest;
import com.pipedream.api.types.Component;
import com.pipedream.api.types.ConfigurePropResponse;
import com.pipedream.api.types.DeployedComponent;
import com.pipedream.api.types.ReloadPropsResponse;

public class TriggersClient {
    protected final ClientOptions clientOptions;

    private final RawTriggersClient rawClient;

    public TriggersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawTriggersClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawTriggersClient withRawResponse() {
        return this.rawClient;
    }

    public SyncPagingIterable<Component> list() {
        return this.rawClient.list().body();
    }

    public SyncPagingIterable<Component> list(TriggersListRequest request) {
        return this.rawClient.list(request).body();
    }

    public SyncPagingIterable<Component> list(TriggersListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    public Component retrieve(String componentId) {
        return this.rawClient.retrieve(componentId).body();
    }

    public Component retrieve(String componentId, RequestOptions requestOptions) {
        return this.rawClient.retrieve(componentId, requestOptions).body();
    }

    public ConfigurePropResponse configureProp(TriggersConfigurePropRequest request) {
        return this.rawClient.configureProp(request).body();
    }

    public ConfigurePropResponse configureProp(TriggersConfigurePropRequest request, RequestOptions requestOptions) {
        return this.rawClient.configureProp(request, requestOptions).body();
    }

    public ReloadPropsResponse reloadProps(TriggersReloadPropsRequest request) {
        return this.rawClient.reloadProps(request).body();
    }

    public ReloadPropsResponse reloadProps(TriggersReloadPropsRequest request, RequestOptions requestOptions) {
        return this.rawClient.reloadProps(request, requestOptions).body();
    }

    public DeployedComponent deploy(DeployTriggerOpts request) {
        return this.rawClient.deploy(request).body();
    }

    public DeployedComponent deploy(DeployTriggerOpts request, RequestOptions requestOptions) {
        return this.rawClient.deploy(request, requestOptions).body();
    }
}
