/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.deployedtriggers.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeployedTriggersDeleteRequest.Builder.class)
public final class DeployedTriggersDeleteRequest {
    private final String externalUserId;

    private final Optional<Boolean> ignoreHookErrors;

    private final Map<String, Object> additionalProperties;

    private DeployedTriggersDeleteRequest(
            String externalUserId, Optional<Boolean> ignoreHookErrors, Map<String, Object> additionalProperties) {
        this.externalUserId = externalUserId;
        this.ignoreHookErrors = ignoreHookErrors;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The external user ID who owns the trigger
     */
    @JsonProperty("external_user_id")
    public String getExternalUserId() {
        return externalUserId;
    }

    /**
     * @return Whether to ignore errors during deactivation hook
     */
    @JsonProperty("ignore_hook_errors")
    public Optional<Boolean> getIgnoreHookErrors() {
        return ignoreHookErrors;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeployedTriggersDeleteRequest && equalTo((DeployedTriggersDeleteRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeployedTriggersDeleteRequest other) {
        return externalUserId.equals(other.externalUserId) && ignoreHookErrors.equals(other.ignoreHookErrors);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.externalUserId, this.ignoreHookErrors);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ExternalUserIdStage builder() {
        return new Builder();
    }

    public interface ExternalUserIdStage {
        /**
         * <p>The external user ID who owns the trigger</p>
         */
        _FinalStage externalUserId(@NotNull String externalUserId);

        Builder from(DeployedTriggersDeleteRequest other);
    }

    public interface _FinalStage {
        DeployedTriggersDeleteRequest build();

        /**
         * <p>Whether to ignore errors during deactivation hook</p>
         */
        _FinalStage ignoreHookErrors(Optional<Boolean> ignoreHookErrors);

        _FinalStage ignoreHookErrors(Boolean ignoreHookErrors);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ExternalUserIdStage, _FinalStage {
        private String externalUserId;

        private Optional<Boolean> ignoreHookErrors = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DeployedTriggersDeleteRequest other) {
            externalUserId(other.getExternalUserId());
            ignoreHookErrors(other.getIgnoreHookErrors());
            return this;
        }

        /**
         * <p>The external user ID who owns the trigger</p>
         * <p>The external user ID who owns the trigger</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("external_user_id")
        public _FinalStage externalUserId(@NotNull String externalUserId) {
            this.externalUserId = Objects.requireNonNull(externalUserId, "externalUserId must not be null");
            return this;
        }

        /**
         * <p>Whether to ignore errors during deactivation hook</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage ignoreHookErrors(Boolean ignoreHookErrors) {
            this.ignoreHookErrors = Optional.ofNullable(ignoreHookErrors);
            return this;
        }

        /**
         * <p>Whether to ignore errors during deactivation hook</p>
         */
        @java.lang.Override
        @JsonSetter(value = "ignore_hook_errors", nulls = Nulls.SKIP)
        public _FinalStage ignoreHookErrors(Optional<Boolean> ignoreHookErrors) {
            this.ignoreHookErrors = ignoreHookErrors;
            return this;
        }

        @java.lang.Override
        public DeployedTriggersDeleteRequest build() {
            return new DeployedTriggersDeleteRequest(externalUserId, ignoreHookErrors, additionalProperties);
        }
    }
}
