/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.deployedtriggers.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeployedTriggersListWebhooksRequest.Builder.class)
public final class DeployedTriggersListWebhooksRequest {
    private final String externalUserId;

    private final Map<String, Object> additionalProperties;

    private DeployedTriggersListWebhooksRequest(String externalUserId, Map<String, Object> additionalProperties) {
        this.externalUserId = externalUserId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The external user ID who owns the trigger
     */
    @JsonProperty("external_user_id")
    public String getExternalUserId() {
        return externalUserId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeployedTriggersListWebhooksRequest
                && equalTo((DeployedTriggersListWebhooksRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeployedTriggersListWebhooksRequest other) {
        return externalUserId.equals(other.externalUserId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.externalUserId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ExternalUserIdStage builder() {
        return new Builder();
    }

    public interface ExternalUserIdStage {
        /**
         * <p>The external user ID who owns the trigger</p>
         */
        _FinalStage externalUserId(@NotNull String externalUserId);

        Builder from(DeployedTriggersListWebhooksRequest other);
    }

    public interface _FinalStage {
        DeployedTriggersListWebhooksRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ExternalUserIdStage, _FinalStage {
        private String externalUserId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DeployedTriggersListWebhooksRequest other) {
            externalUserId(other.getExternalUserId());
            return this;
        }

        /**
         * <p>The external user ID who owns the trigger</p>
         * <p>The external user ID who owns the trigger</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("external_user_id")
        public _FinalStage externalUserId(@NotNull String externalUserId) {
            this.externalUserId = Objects.requireNonNull(externalUserId, "externalUserId must not be null");
            return this;
        }

        @java.lang.Override
        public DeployedTriggersListWebhooksRequest build() {
            return new DeployedTriggersListWebhooksRequest(externalUserId, additionalProperties);
        }
    }
}
