/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.deployedtriggers.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateTriggerWebhooksOpts.Builder.class)
public final class UpdateTriggerWebhooksOpts {
    private final String externalUserId;

    private final List<String> webhookUrls;

    private final Map<String, Object> additionalProperties;

    private UpdateTriggerWebhooksOpts(
            String externalUserId, List<String> webhookUrls, Map<String, Object> additionalProperties) {
        this.externalUserId = externalUserId;
        this.webhookUrls = webhookUrls;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The external user ID who owns the trigger
     */
    @JsonProperty("external_user_id")
    public String getExternalUserId() {
        return externalUserId;
    }

    /**
     * @return Array of webhook URLs to set
     */
    @JsonProperty("webhook_urls")
    public List<String> getWebhookUrls() {
        return webhookUrls;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateTriggerWebhooksOpts && equalTo((UpdateTriggerWebhooksOpts) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateTriggerWebhooksOpts other) {
        return externalUserId.equals(other.externalUserId) && webhookUrls.equals(other.webhookUrls);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.externalUserId, this.webhookUrls);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ExternalUserIdStage builder() {
        return new Builder();
    }

    public interface ExternalUserIdStage {
        /**
         * <p>The external user ID who owns the trigger</p>
         */
        _FinalStage externalUserId(@NotNull String externalUserId);

        Builder from(UpdateTriggerWebhooksOpts other);
    }

    public interface _FinalStage {
        UpdateTriggerWebhooksOpts build();

        /**
         * <p>Array of webhook URLs to set</p>
         */
        _FinalStage webhookUrls(List<String> webhookUrls);

        _FinalStage addWebhookUrls(String webhookUrls);

        _FinalStage addAllWebhookUrls(List<String> webhookUrls);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ExternalUserIdStage, _FinalStage {
        private String externalUserId;

        private List<String> webhookUrls = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UpdateTriggerWebhooksOpts other) {
            externalUserId(other.getExternalUserId());
            webhookUrls(other.getWebhookUrls());
            return this;
        }

        /**
         * <p>The external user ID who owns the trigger</p>
         * <p>The external user ID who owns the trigger</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("external_user_id")
        public _FinalStage externalUserId(@NotNull String externalUserId) {
            this.externalUserId = Objects.requireNonNull(externalUserId, "externalUserId must not be null");
            return this;
        }

        /**
         * <p>Array of webhook URLs to set</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllWebhookUrls(List<String> webhookUrls) {
            this.webhookUrls.addAll(webhookUrls);
            return this;
        }

        /**
         * <p>Array of webhook URLs to set</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addWebhookUrls(String webhookUrls) {
            this.webhookUrls.add(webhookUrls);
            return this;
        }

        /**
         * <p>Array of webhook URLs to set</p>
         */
        @java.lang.Override
        @JsonSetter(value = "webhook_urls", nulls = Nulls.SKIP)
        public _FinalStage webhookUrls(List<String> webhookUrls) {
            this.webhookUrls.clear();
            this.webhookUrls.addAll(webhookUrls);
            return this;
        }

        @java.lang.Override
        public UpdateTriggerWebhooksOpts build() {
            return new UpdateTriggerWebhooksOpts(externalUserId, webhookUrls, additionalProperties);
        }
    }
}
