/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.users;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.ObjectMappers;
import com.pipedream.api.core.PipedreamApiApiException;
import com.pipedream.api.core.PipedreamApiException;
import com.pipedream.api.core.PipedreamApiHttpResponse;
import com.pipedream.api.core.RequestOptions;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawUsersClient {
    protected final ClientOptions clientOptions;

    public RawUsersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public PipedreamApiHttpResponse<Void> deleteExternalUser(String externalUserId) {
        return deleteExternalUser(externalUserId, null);
    }

    public PipedreamApiHttpResponse<Void> deleteExternalUser(String externalUserId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/connect")
                .addPathSegment(clientOptions.projectId())
                .addPathSegments("users")
                .addPathSegment(externalUserId)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PipedreamApiHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PipedreamApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PipedreamApiException("Network error executing HTTP request", e);
        }
    }
}
