/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.accounts;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.resources.accounts.requests.AccountsListRequest;
import com.pipedream.api.resources.accounts.requests.AccountsRetrieveRequest;
import com.pipedream.api.resources.accounts.requests.CreateAccountOpts;
import com.pipedream.api.types.Account;

public class AccountsClient {
    protected final ClientOptions clientOptions;

    private final RawAccountsClient rawClient;

    public AccountsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAccountsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAccountsClient withRawResponse() {
        return this.rawClient;
    }

    public SyncPagingIterable<Account> list() {
        return this.rawClient.list().body();
    }

    public SyncPagingIterable<Account> list(AccountsListRequest request) {
        return this.rawClient.list(request).body();
    }

    public SyncPagingIterable<Account> list(AccountsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    public Account create(CreateAccountOpts request) {
        return this.rawClient.create(request).body();
    }

    public Account create(CreateAccountOpts request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    public Account retrieve(String accountId) {
        return this.rawClient.retrieve(accountId).body();
    }

    public Account retrieve(String accountId, AccountsRetrieveRequest request) {
        return this.rawClient.retrieve(accountId, request).body();
    }

    public Account retrieve(String accountId, AccountsRetrieveRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(accountId, request, requestOptions).body();
    }

    public void delete(String accountId) {
        this.rawClient.delete(accountId).body();
    }

    public void delete(String accountId, RequestOptions requestOptions) {
        this.rawClient.delete(accountId, requestOptions).body();
    }

    public void deleteByApp(String appId) {
        this.rawClient.deleteByApp(appId).body();
    }

    public void deleteByApp(String appId, RequestOptions requestOptions) {
        this.rawClient.deleteByApp(appId, requestOptions).body();
    }
}
