/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.proxy.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProxyDeleteRequest.Builder.class)
public final class ProxyDeleteRequest {
    private final String externalUserId;

    private final String accountId;

    private final Map<String, Object> additionalProperties;

    private ProxyDeleteRequest(String externalUserId, String accountId, Map<String, Object> additionalProperties) {
        this.externalUserId = externalUserId;
        this.accountId = accountId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The external user ID for the proxy request
     */
    @JsonProperty("external_user_id")
    public String getExternalUserId() {
        return externalUserId;
    }

    /**
     * @return The account ID to use for authentication
     */
    @JsonProperty("account_id")
    public String getAccountId() {
        return accountId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProxyDeleteRequest && equalTo((ProxyDeleteRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProxyDeleteRequest other) {
        return externalUserId.equals(other.externalUserId) && accountId.equals(other.accountId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.externalUserId, this.accountId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ExternalUserIdStage builder() {
        return new Builder();
    }

    public interface ExternalUserIdStage {
        /**
         * <p>The external user ID for the proxy request</p>
         */
        AccountIdStage externalUserId(@NotNull String externalUserId);

        Builder from(ProxyDeleteRequest other);
    }

    public interface AccountIdStage {
        /**
         * <p>The account ID to use for authentication</p>
         */
        _FinalStage accountId(@NotNull String accountId);
    }

    public interface _FinalStage {
        ProxyDeleteRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ExternalUserIdStage, AccountIdStage, _FinalStage {
        private String externalUserId;

        private String accountId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ProxyDeleteRequest other) {
            externalUserId(other.getExternalUserId());
            accountId(other.getAccountId());
            return this;
        }

        /**
         * <p>The external user ID for the proxy request</p>
         * <p>The external user ID for the proxy request</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("external_user_id")
        public AccountIdStage externalUserId(@NotNull String externalUserId) {
            this.externalUserId = Objects.requireNonNull(externalUserId, "externalUserId must not be null");
            return this;
        }

        /**
         * <p>The account ID to use for authentication</p>
         * <p>The account ID to use for authentication</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("account_id")
        public _FinalStage accountId(@NotNull String accountId) {
            this.accountId = Objects.requireNonNull(accountId, "accountId must not be null");
            return this;
        }

        @java.lang.Override
        public ProxyDeleteRequest build() {
            return new ProxyDeleteRequest(externalUserId, accountId, additionalProperties);
        }
    }
}
