/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.apps;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.resources.apps.requests.AppsListRequest;
import com.pipedream.api.types.App;
import com.pipedream.api.types.GetAppResponse;

public class AppsClient {
    protected final ClientOptions clientOptions;

    private final RawAppsClient rawClient;

    public AppsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAppsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAppsClient withRawResponse() {
        return this.rawClient;
    }

    public SyncPagingIterable<App> list() {
        return this.rawClient.list().body();
    }

    public SyncPagingIterable<App> list(AppsListRequest request) {
        return this.rawClient.list(request).body();
    }

    public SyncPagingIterable<App> list(AppsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    public GetAppResponse retrieve(String appId) {
        return this.rawClient.retrieve(appId).body();
    }

    public GetAppResponse retrieve(String appId, RequestOptions requestOptions) {
        return this.rawClient.retrieve(appId, requestOptions).body();
    }
}
