/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.actions;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.resources.actions.requests.ActionsConfigurePropRequest;
import com.pipedream.api.resources.actions.requests.ActionsListRequest;
import com.pipedream.api.resources.actions.requests.ActionsReloadPropsRequest;
import com.pipedream.api.resources.actions.requests.RunActionOpts;
import com.pipedream.api.types.Component;
import com.pipedream.api.types.ConfigurePropResponse;
import com.pipedream.api.types.ReloadPropsResponse;
import com.pipedream.api.types.RunActionResponse;

public class ActionsClient {
    protected final ClientOptions clientOptions;

    private final RawActionsClient rawClient;

    public ActionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawActionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawActionsClient withRawResponse() {
        return this.rawClient;
    }

    public SyncPagingIterable<Component> list() {
        return this.rawClient.list().body();
    }

    public SyncPagingIterable<Component> list(ActionsListRequest request) {
        return this.rawClient.list(request).body();
    }

    public SyncPagingIterable<Component> list(ActionsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    public Component retrieve(String componentId) {
        return this.rawClient.retrieve(componentId).body();
    }

    public Component retrieve(String componentId, RequestOptions requestOptions) {
        return this.rawClient.retrieve(componentId, requestOptions).body();
    }

    public ConfigurePropResponse configureProp(ActionsConfigurePropRequest request) {
        return this.rawClient.configureProp(request).body();
    }

    public ConfigurePropResponse configureProp(ActionsConfigurePropRequest request, RequestOptions requestOptions) {
        return this.rawClient.configureProp(request, requestOptions).body();
    }

    public ReloadPropsResponse reloadProps(ActionsReloadPropsRequest request) {
        return this.rawClient.reloadProps(request).body();
    }

    public ReloadPropsResponse reloadProps(ActionsReloadPropsRequest request, RequestOptions requestOptions) {
        return this.rawClient.reloadProps(request, requestOptions).body();
    }

    public RunActionResponse run(RunActionOpts request) {
        return this.rawClient.run(request).body();
    }

    public RunActionResponse run(RunActionOpts request, RequestOptions requestOptions) {
        return this.rawClient.run(request, requestOptions).body();
    }
}
