/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.oauthtokens;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.resources.oauthtokens.requests.CreateOAuthTokenOpts;
import com.pipedream.api.types.CreateOAuthTokenResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncOauthTokensClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawOauthTokensClient rawClient;

    public AsyncOauthTokensClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawOauthTokensClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawOauthTokensClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<CreateOAuthTokenResponse> create(CreateOAuthTokenOpts request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    public CompletableFuture<CreateOAuthTokenResponse> create(
            CreateOAuthTokenOpts request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }
}
