/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.components.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import com.pipedream.api.types.ReloadPropsOpts;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ComponentsReloadPropsRequest.Builder.class)
public final class ComponentsReloadPropsRequest {
    private final Optional<String> asyncHandle;

    private final ReloadPropsOpts body;

    private final Map<String, Object> additionalProperties;

    private ComponentsReloadPropsRequest(
            Optional<String> asyncHandle, ReloadPropsOpts body, Map<String, Object> additionalProperties) {
        this.asyncHandle = asyncHandle;
        this.body = body;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("x-async-handle")
    public Optional<String> getAsyncHandle() {
        return asyncHandle;
    }

    @JsonProperty("body")
    public ReloadPropsOpts getBody() {
        return body;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ComponentsReloadPropsRequest && equalTo((ComponentsReloadPropsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ComponentsReloadPropsRequest other) {
        return asyncHandle.equals(other.asyncHandle) && body.equals(other.body);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.asyncHandle, this.body);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static BodyStage builder() {
        return new Builder();
    }

    public interface BodyStage {
        _FinalStage body(@NotNull ReloadPropsOpts body);

        Builder from(ComponentsReloadPropsRequest other);
    }

    public interface _FinalStage {
        ComponentsReloadPropsRequest build();

        _FinalStage asyncHandle(Optional<String> asyncHandle);

        _FinalStage asyncHandle(String asyncHandle);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements BodyStage, _FinalStage {
        private ReloadPropsOpts body;

        private Optional<String> asyncHandle = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ComponentsReloadPropsRequest other) {
            asyncHandle(other.getAsyncHandle());
            body(other.getBody());
            return this;
        }

        @java.lang.Override
        @JsonSetter("body")
        public _FinalStage body(@NotNull ReloadPropsOpts body) {
            this.body = Objects.requireNonNull(body, "body must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage asyncHandle(String asyncHandle) {
            this.asyncHandle = Optional.ofNullable(asyncHandle);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "x-async-handle", nulls = Nulls.SKIP)
        public _FinalStage asyncHandle(Optional<String> asyncHandle) {
            this.asyncHandle = asyncHandle;
            return this;
        }

        @java.lang.Override
        public ComponentsReloadPropsRequest build() {
            return new ComponentsReloadPropsRequest(asyncHandle, body, additionalProperties);
        }
    }
}
