/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.tokens;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.resources.tokens.requests.CreateTokenOpts;
import com.pipedream.api.resources.tokens.requests.TokensValidateRequest;
import com.pipedream.api.types.CreateTokenResponse;
import com.pipedream.api.types.ValidateTokenResponse;

public class TokensClient {
    protected final ClientOptions clientOptions;

    private final RawTokensClient rawClient;

    public TokensClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawTokensClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawTokensClient withRawResponse() {
        return this.rawClient;
    }

    public CreateTokenResponse create(CreateTokenOpts request) {
        return this.rawClient.create(request).body();
    }

    public CreateTokenResponse create(CreateTokenOpts request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    public ValidateTokenResponse validate(String ctok) {
        return this.rawClient.validate(ctok).body();
    }

    public ValidateTokenResponse validate(String ctok, TokensValidateRequest request) {
        return this.rawClient.validate(ctok, request).body();
    }

    public ValidateTokenResponse validate(String ctok, TokensValidateRequest request, RequestOptions requestOptions) {
        return this.rawClient.validate(ctok, request, requestOptions).body();
    }
}
