/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.core;

public final class Environment {
    public static final Environment CANARY = new Environment("https://api2.pipedream.com");

    public static final Environment DEV = new Environment("https://api.${DEV_NAMESPACE}.gkes.pipedream.net");

    public static final Environment PROD = new Environment("https://api.pipedream.com");

    private final String url;

    private Environment(String url) {
        this.url = url;
    }

    public String getUrl() {
        return this.url;
    }

    public static Environment custom(String url) {
        return new Environment(url);
    }
}
