/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class PipedreamApiException extends RuntimeException {
    public PipedreamApiException(String message) {
        super(message);
    }

    public PipedreamApiException(String message, Exception e) {
        super(message, e);
    }
}
